name: Vacation Calculator CI with Maven

on:
  push:
    branches: [ "main" ]

permissions:
  packages: write

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Java setup
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'
          cache: 'maven'

      - name: Build with Maven
        run: mvn package

      - name: Log in to the Container registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Build and push the scrapper Docker image
        run: |
          docker build -t ghcr.io/romanolontsev/vacation-pay-calculator/calculator:latest .
          docker push ghcr.io/romanolontsev/vacation-pay-calculator/calculator:latest